tic
PATH="D:\Foxconn_IAI大賽\Test\Test\Test_";
SAVEPATH="D:\Foxconn_IAI大賽\Test\denoise\";
TPYE=".csv";
for i=1:315
    X_temp=readtable(PATH+num2str(i,'%.3d')+TPYE);
    %去除线性趋势
    for j=1:6
        X_temp{:,j}=detrend(X_temp{:,j});
    end
    %去除噪声
    X_temp{:,1:3} = wdenoise(X_temp{:,1:3},5, ...
        'Wavelet', 'sym4', ...
        'DenoisingMethod', 'UniversalThreshold', ...
        'ThresholdRule', 'Soft', ...
        'NoiseEstimate', 'LevelDependent');
    
    X_temp{:,4:6}= wdenoise(X_temp{:,4:6},4, ...
        'Wavelet', 'sym4', ...
        'DenoisingMethod', 'UniversalThreshold', ...
        'ThresholdRule', 'Hard', ...
        'NoiseEstimate', 'LevelIndependent');
    
    X_temp{:,7} = wdenoise(X_temp{:,7},4, ...
        'Wavelet', 'sym5', ...
        'DenoisingMethod', 'UniversalThreshold', ...
        'ThresholdRule', 'Soft', ...
        'NoiseEstimate', 'LevelIndependent');

    writetable(X_temp,(SAVEPATH+num2str(i,'%.3d')+TPYE))

end
toc
